# ============================================================================
# FILE: config/config.yaml (FIXED WITH YOUR PROJECT ID)
# ============================================================================

# TROPOMI Methane Pipeline Configuration

# Google Earth Engine settings
gee:
  service_account_file: null  
  project_id: "sodium-lore-456715-i3"  # CHANGE THIS to your actual project ID
  
# Data collection parameters
data:
  start_date: "2023-06-01"
  end_date: "2023-06-03" 
  region_of_interest:
    type: "bbox"
    #coordinates: [4.0, 51.5, 5.0, 52.5]  # Netherlands region
    coordinates: [-103.0, 31.5, -101.5, 33.0]  # texas

  
# TROPOMI specific settings
tropomi:
  collection: "COPERNICUS/S5P/OFFL/L3_CH4"
  quality_threshold: 0.5
  cloud_fraction_max: 0.3
  qa_flags: ["GOOD"]
  
# Detection parameters
detection:
  background_percentile: 50
  anomaly_threshold: 1
  min_enhancement: 10.0
  spatial_window: 5
  temporal_window: 7
  
# Output settings
output:
  base_path: "./data/outputs"
  export_formats: ["geojson", "csv", "netcdf"]
  create_plots: true
  
# Visualization settings
visualization:
  colormap: "plasma"
  dpi: 300
  figsize: [12, 8]