# ============================================================================
# FILE: config/config.yaml (FIXED VERSION)
# ============================================================================

# TROPOMI Methane Pipeline Configuration

# Google Earth Engine settings
gee:
  service_account_file: null  # Path to service account JSON file
  project_id: "your-gee-project-id"  # CHANGE THIS to your actual GEE project ID
  
# Data collection parameters
data:
  start_date: "2023-06-01"  # Changed to shorter period for testing
  end_date: "2023-06-07"    # Just one week for initial testing
  region_of_interest:
    type: "bbox"  # bbox or polygon
    coordinates: [4.0, 51.5, 5.0, 52.5]  # Netherlands region (better for your location)
  
# TROPOMI specific settings
tropomi:
  collection: "COPERNICUS/S5P/OFFL/L3_CH4"
  quality_threshold: 0.5
  cloud_fraction_max: 0.3
  qa_flags: ["GOOD"]
  
# Detection parameters
detection:
  background_percentile: 50
  anomaly_threshold: 2.0  # standard deviations
  min_enhancement: 20.0   # ppb
  spatial_window: 5       # pixels
  temporal_window: 7      # days
  
# Output settings
output:
  base_path: "./data/outputs"
  export_formats: ["geojson", "csv", "netcdf"]
  create_plots: true
  
# Visualization settings
visualization:
  colormap: "plasma"
  dpi: 300
  figsize: [12, 8]

# ============================================================================
# Additional Configuration Options for Advanced Users
# ============================================================================

# Alternative regions for testing (uncomment one to use)
# 
# # Houston Oil & Gas Region
# data:
#   region_of_interest:
#     type: "bbox"
#     coordinates: [-95.5, 29.0, -94.5, 30.0]
#
# # Permian Basin (Major Oil/Gas Region) 
# data:
#   region_of_interest:
#     type: "bbox"
#     coordinates: [-103.0, 31.5, -101.5, 33.0]
#
# # Los Angeles Basin
# data:
#   region_of_interest:
#     type: "bbox"
#     coordinates: [-118.5, 33.5, -117.5, 34.5]

# ============================================================================
# Configuration for your specific use case based on spatial_mapping repo
# ============================================================================

# Enhanced detection for urban/industrial areas
# detection:
#   background_percentile: 25      # More sensitive background
#   anomaly_threshold: 1.8         # Lower threshold for urban areas
#   min_enhancement: 15.0          # Catch smaller sources
#   spatial_window: 3              # Smaller window for dense areas
#   temporal_window: 5             # Shorter persistence requirement

# High-quality output settings for research/publication
# output:
#   base_path: "./results"
#   export_formats: ["geojson", "csv", "netcdf", "shapefile"]
#   create_plots: true
#   
# visualization:
#   colormap: "viridis"            # Better for scientific publications
#   dpi: 600                       # High resolution for papers
#   figsize: [15, 10]              # Larger figures