# TROPOMI Configuration - Optimized for your actual data
# Based on analysis showing enhancements up to ~60 ppb

gee:
  service_account_file: null
  project_id: "sodium-lore-456715-i3"
  
data:
  start_date: "2023-06-01"
  end_date: "2023-06-07"
  region_of_interest:
    type: "bbox"
    coordinates: [-103.0, 31.5, -101.5, 33.0]
  
tropomi:
  collection: "COPERNICUS/S5P/OFFL/L3_CH4"
  quality_threshold: 0.1
  cloud_fraction_max: 0.8
  qa_flags: ["GOOD", "MEDIUM"]
  
# Detection parameters - Tuned for your data showing max ~60 ppb enhancements
detection:
  background_percentile: 50
  anomaly_threshold: 0.5      # Very low - only 0.5 std deviations
  min_enhancement: 5.0        # Based on your data showing clear >5 ppb areas
  spatial_window: 3
  temporal_window: 2          # Reduced - only need to appear in 2+ time steps
  
output:
  base_path: "./data/outputs"
  export_formats: ["csv", "geojson"]
  create_plots: true
  
visualization:
  colormap: "plasma"
  dpi: 150
  figsize: [10, 6]